package com.gooben.yxt.service.api.ws.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-12T16:19:09.269+08:00
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", name = "WsItfTask")
@XmlSeeAlso({ObjectFactory.class})
public interface WsItfTask {

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSentResultCallResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    public GetSentResultCallResponse getSentResultCall(

        @WebParam(partName = "parameters", name = "getSentResultCall", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/")
        GetSentResultCall parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true)
        java.lang.String token
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSubmitResultResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    public GetSubmitResultResponse getSubmitResult(

        @WebParam(partName = "parameters", name = "getSubmitResult", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/")
        GetSubmitResult parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true)
        java.lang.String token
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "addFileResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    public AddFileResponse addFile(

        @WebParam(partName = "parameters", name = "addFile", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/")
        AddFile parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true)
        java.lang.String token
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSentTaskResultCallResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    public GetSentTaskResultCallResponse getSentTaskResultCall(

        @WebParam(partName = "parameters", name = "getSentTaskResultCall", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/")
        GetSentTaskResultCall parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true)
        java.lang.String token
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSentTaskResultSmsResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    public GetSentTaskResultSmsResponse getSentTaskResultSms(

        @WebParam(partName = "parameters", name = "getSentTaskResultSms", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/")
        GetSentTaskResultSms parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true)
        java.lang.String token
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "submitTaskResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    public SubmitTaskResponse submitTask(

        @WebParam(partName = "parameters", name = "submitTask", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/")
        SubmitTask parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true)
        java.lang.String token
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSentResultSmsResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    public GetSentResultSmsResponse getSentResultSms(

        @WebParam(partName = "parameters", name = "getSentResultSms", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/")
        GetSentResultSms parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true)
        java.lang.String token
    );

    @WebMethod
    @RequestWrapper(localName = "authorization", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", className = "com.gooben.yxt.service.api.ws.v1.Authorization")
    @ResponseWrapper(localName = "authorizationResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", className = "com.gooben.yxt.service.api.ws.v1.AuthorizationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.gooben.yxt.service.api.ws.v1.InterfaceResult authorization(

        @WebParam(name = "userCode", targetNamespace = "")
        java.lang.String userCode,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "unixtick", targetNamespace = "")
        long unixtick
    );

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getSmsReceiveResponse", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", partName = "parameters")
    public GetSmsReceiveResponse getSmsReceive(

        @WebParam(partName = "parameters", name = "getSmsReceive", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/")
        GetSmsReceive parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://v1.ws.api.service.yxt.gooben.com/", header = true)
        java.lang.String token
    );
}
