package com.gooben.yxt.service.api.ws.v1.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

///**
// * This class was generated by Apache CXF 3.4.3
// * 2021-04-12T16:19:09.318+08:00
// * Generated source version: 3.4.3
// *
// */
@WebServiceClient(name = "WsItfTask",
                  wsdlLocation = "file:/Users/paul/code/fox/common/src/main/resources/WsItfTask2.wsdl",
                  targetNamespace = "http://impl.v1.ws.api.service.yxt.gooben.com/")
public class WsItfTask extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.v1.ws.api.service.yxt.gooben.com/", "WsItfTask");
    public final static QName WsItfTaskImplPort = new QName("http://impl.v1.ws.api.service.yxt.gooben.com/", "WsItfTaskImplPort");
    static {
        URL url = null;
        //            url = new URL("file:WsItfTask.wsdl");
//            url = new URL("http://115.239.137.23:9501/ws/v1?wsdl");
        WSDL_LOCATION = url;
    }

    public WsItfTask(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsItfTask(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsItfTask() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WsItfTask(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsItfTask(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsItfTask(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WsItfTask
     */
    @WebEndpoint(name = "WsItfTaskImplPort")
    public com.gooben.yxt.service.api.ws.v1.WsItfTask getWsItfTaskImplPort() {
        return super.getPort(WsItfTaskImplPort, com.gooben.yxt.service.api.ws.v1.WsItfTask.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsItfTask
     */
    @WebEndpoint(name = "WsItfTaskImplPort")
    public com.gooben.yxt.service.api.ws.v1.WsItfTask getWsItfTaskImplPort(WebServiceFeature... features) {
        return super.getPort(WsItfTaskImplPort, com.gooben.yxt.service.api.ws.v1.WsItfTask.class, features);
    }

}
